name: Vale documentation linting

on:
  pull_request:
    paths:
      - '**.md'
  push:
    branches:
      - master
    paths:
      - '**.md'

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Vale
        uses: errata-ai/vale-action@v2
        with:
          files: '["*.md", "utils/*.md", "research/*.md"]'
          fail_on_error: false
          vale_flags: "--minAlertLevel=error"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
